[env]
CARGO_WORKSPACE_DIR = { value = "", relative = true }

[alias]
c = "check --workspace --all-targets"
t = "nextest run -P default --retries 0 --no-tests warn --all-targets"
clippy-wrapper = "run -q --package clippy-wrapper --"

# linting
lint = "clippy-wrapper lint"
fixit = "clippy-wrapper fixit"
