# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"
includes:
  lib:
    taskfile: "../../tasks/rust-lib.yaml"
    flatten: true
    vars:
      PACKAGE: &package "clippy-wrapper"
